#----------------------------------------------------------
# common
#----------------------------------------------------------

postgres: &postgres
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: 5
  port: 5432

sqlite: &sqlite
  adapter: sqlite3
  timeout: 5000


#----------------------------------------------------------
# local
#----------------------------------------------------------

development:
  <<: *sqlite
  database: caracal_example_development

test:
  <<: *sqlite
  database: caracal_example_test
